

export default [
    { value: 	2	, label: '	ECO TOCOGINECOLOGICA	' },
{ value: 	3	, label: '	ECO OBSTETRICA  2 - 3 TRIMESTRE	' },
{ value: 	4	, label: '	ECO TIROIDEA	' },
{ value: 	5	, label: '	ECO PARTES BLANDAS	' },
{ value: 	6	, label: '	ECO OSEA	' },
{ value: 	7	, label: '	ECO MUSCULAR	' },
{ value: 	8	, label: '	ECO CADERA	' },
{ value: 	9	, label: '	ECO CEREBRAL	' },
{ value: 	10	, label: '	ECO PAROTIDEA	' },
{ value: 	11	, label: '	ECO ABDOMINAL P/NIÑOS	' },
{ value: 	12	, label: '	ECOCARDIOGRAMA BIDIMENSIONAL	' },
{ value: 	13	, label: '	ECO DOPPLER ABDOMINAL	' },
{ value: 	14	, label: '	ECO DOPPLER RENAL	' },
{ value: 	16	, label: '	ECO DOPPLER CAROTIDEO	' },
{ value: 	17	, label: '	ECO TESTICULAR	' },
{ value: 	18	, label: '	ECO DOPPLER TESTICULAR	' },
{ value: 	19	, label: '	ECO DOPPLER OBSTETRICO	' },
{ value: 	20	, label: '	RX TORAX F	' },
{ value: 	21	, label: '	RX TORAX FYP	' },
{ value: 	22	, label: '	RX CRANEO FYP	' },
{ value: 	23	, label: '	RX CERVICAL FYP	' },
{ value: 	24	, label: '	RX HOMBRO FYA	' },
{ value: 	25	, label: '	RX DIRECTA DE ABDOMEN PIE	' },
{ value: 	26	, label: '	RX DIRECTA ABDOMEN PIE Y ACOST	' },
{ value: 	27	, label: '	RX BRAZO FYP	' },
{ value: 	28	, label: '	RX ANTEBRAZO FYP	' },
{ value: 	29	, label: '	RX MUÑECA FYP	' },
{ value: 	30	, label: '	RX MANO FYO	' },
{ value: 	31	, label: '	RX PIERNA FYP	' },
{ value: 	32	, label: '	RX RODILLA FYP	' },
{ value: 	33	, label: '	RX FEMUR FYP	' },
{ value: 	34	, label: '	RX PIE F Y O	' },
{ value: 	35	, label: '	RX AMBAS MANOS FYP	' },
{ value: 	36	, label: '	RX AMBOS PIES FYP	' },
{ value: 	37	, label: '	RX AMBAS RODILLAS FYP	' },
{ value: 	38	, label: '	RX CODO FYP	' },
{ value: 	39	, label: '	RX HUMERO FYP	' },
{ value: 	40	, label: '	RX SPN	' },
{ value: 	41	, label: '	RX CAVUM	' },
{ value: 	42	, label: '	RX SPN/CAVUM	' },
{ value: 	43	, label: '	RX HIRTZ	' },
{ value: 	44	, label: '	RX SCHULLER	' },
{ value: 	45	, label: '	MAMOGRAFIA BILATERAL C/ PROYECCION AXILAR	' },
{ value: 	46	, label: '	MARCACION CON ARPON	' },
{ value: 	47	, label: '	MAGNIFICACION Y COMPRESION C/ PROYECCION AXILAR	' },
{ value: 	48	, label: '	TAC CEREBRO S/CTE MULTICORTE	' },
{ value: 	49	, label: '	TAC CEREBRO C/CTE MULTICORTE	' },
{ value: 	50	, label: '	TAC TORAX S/CTE MULTICORTE	' },
{ value: 	51	, label: '	TAC TORAX C/CTE MULTICORTE	' },
{ value: 	52	, label: '	TAC ABDOMEN C/CTE MULTICORTE	' },
{ value: 	53	, label: '	TAC ABDOMEN S/CTE MULTICORTE	' },
{ value: 	54	, label: '	TAC MAXILAR INFERIOR MULTICORTE	' },
{ value: 	55	, label: '	TAC MAXILAR SUPERIOR MULTICORTE	' },
{ value: 	56	, label: '	TAC AMBOS MAXILARES MULTICORTE	' },
{ value: 	57	, label: '	TAC AMBOS OIDOS MULTICORTE	' },
{ value: 	58	, label: '	TAC SPN MULTICORTE	' },
{ value: 	59	, label: '	TAC ABOMEN/PELVIS MULTICORTE	' },
{ value: 	60	, label: '	TAC ORBITA MULTICORTE	' },
{ value: 	62	, label: '	TAC COLUMNA CERVICAL MULTICORTE	' },
{ value: 	63	, label: '	TAC COLUMNA DORSAL MULTICORTE	' },
{ value: 	64	, label: '	TAC COLUMNA LUMBAR MULTICORTE	' },
{ value: 	65	, label: '	TAC COLUMNA LUMBOSACRA MULTICORTE	' },
{ value: 	66	, label: '	TAC UROTAC MULTICORTE	' },
{ value: 	67	, label: '	RX CORTES TAC	' },
{ value: 	71	, label: '	ECO PROSTATICA TRANSRECTAL	' },
{ value: 	72	, label: '	ECO TRANSVAGINAL	' },
{ value: 	73	, label: '	RX EED	' },
{ value: 	74	, label: '	RX COLON POR ENEMA DOBLE	' },
{ value: 	75	, label: '	RX COLON POR ENEMA SIMPLE	' },
{ value: 	76	, label: '	RX TRANSITO INTESTINO DELGADO	' },
{ value: 	77	, label: '	RX TRANSITO FARINGOESOFAGICO	' },
{ value: 	78	, label: '	CINEDEGLUCION	' },
{ value: 	79	, label: '	ECO MAMARIA	' },
{ value: 	80	, label: '	ECO RENAL	' },
{ value: 	81	, label: '	ECO RENAL Y VESICAL	' },
{ value: 	82	, label: '	ECO RENAL Y VESICOPROSTATICA (C/ RES POST MICCIONAL)	' },
{ value: 	83	, label: '	PUNCION TIROIDEA	' },
{ value: 	84	, label: '	PUNCION PROSTATICA	' },
{ value: 	85	, label: '	PUNCION MAMARIA	' },
{ value: 	86	, label: '	ECO PROSTATICA	' },
{ value: 	87	, label: '	UROGRAMA	' },
{ value: 	88	, label: '	CISTOURETROGRAFIA	' },
{ value: 	89	, label: '	ECO DOPPLER DE MMII ARTERIAL	' },
{ value: 	90	, label: '	RX CADERA FYA	' },
{ value: 	92	, label: '	RX DORSAL FYP	' },
{ value: 	93	, label: '	RX LUMBAR FYP	' },
{ value: 	94	, label: '	RX LUMBOSACRA FYP	' },
{ value: 	95	, label: '	RX PANORAMICA PELVIS	' },
{ value: 	101	, label: '	PUNCION HIGADO	' },
{ value: 	102	, label: '	PUNCION PLEURAL	' },
{ value: 	103	, label: '	PUNCION DE COLUMNA	' },
{ value: 	104	, label: '	PUNCION PIERNA	' },
{ value: 	105	, label: '	RX TOBILLO F Y P	' },
{ value: 	106	, label: '	RX HUESOS PROPIOS DE LA NARIZ	' },
{ value: 	107	, label: '	ECO OCULAR	' },
{ value: 	108	, label: '	COLANGIOGRAFIA TRANSKERR	' },
{ value: 	109	, label: '	COLOCACIÓN DE CATÉTER	' },
{ value: 	110	, label: '	RX CIRUGIA	' },
{ value: 	111	, label: '	PUNCION RENAL	' },
{ value: 	112	, label: '	TAC MUÑECA MULTICORTE	' },
{ value: 	114	, label: '	PAPILOTOMIA	' },
{ value: 	115	, label: '	RADIOSCOPIA	' },
{ value: 	116	, label: '	ECO PLEURAL	' },
{ value: 	117	, label: '	ECO HEPATOBILIAR	' },
{ value: 	118	, label: '	ECO INGUINAL	' },
{ value: 	119	, label: '	ECO CODO	' },
{ value: 	120	, label: '	PUNCION OSEA	' },
{ value: 	122	, label: '	RADIOSCOPIA	' },
{ value: 	123	, label: '	ECO HUECO POPLITEO	' },
{ value: 	124	, label: '	ECO CUELLO	' },
{ value: 	125	, label: '	TAC CARA MULTICORTE	' },
{ value: 	126	, label: '	PUNCION LIQUIDO ASCITICO	' },
{ value: 	127	, label: '	PUNCION QUISTE DE OVARIO	' },
{ value: 	130	, label: '	TAC MANO MULTICORTE	' },
{ value: 	131	, label: '	RX TOBILLO FYP	' },
{ value: 	132	, label: '	ECO DOPPLER MMSUPERIOR/ES	' },
{ value: 	133	, label: '	RESECCION TUMORAL	' },
{ value: 	134	, label: '	PUNCION PULMONAR	' },
{ value: 	135	, label: '	PUNCION ABDOMINAL	' },
{ value: 	136	, label: '	FISTULOGRAFIA	' },
{ value: 	137	, label: '	RX ORBITA	' },
{ value: 	138	, label: '	TAC RODILLA MULTICORTE	' },
{ value: 	139	, label: '	RX OIDO	' },
{ value: 	141	, label: '	RX MACIZO FACIAL	' },
{ value: 	142	, label: '	RX HUESOS PROPIOS DE LA NARIZ	' },
{ value: 	147	, label: '	PUNCION DE COLECCION	' },
{ value: 	148	, label: '	NEFROSTOMIA	' },
{ value: 	151	, label: '	ECOCARDIOGRAMA DOPPLER FETAL	' },
{ value: 	152	, label: '	VIDEOFLUOROSCOPIA	' },
{ value: 	154	, label: '	ECO HEPATOBILIAR	' },
{ value: 	155	, label: '	TAC DE AMBOS MAXILARES MULTICORTE	' },
{ value: 	156	, label: '	ECO OBSTETRICA DEL 1 TRIMESTRE	' },
{ value: 	158	, label: '	TILT-TEST	' },
{ value: 	159	, label: '	ECOCARDIOGRAMA BIDIMENSIONAL P/NIÑOS	' },
{ value: 	160	, label: '	ECO DOPPLER CARDIACO	' },
{ value: 	161	, label: '	PIELOGRAFIA DESCENDENTE	' },
{ value: 	163	, label: '	ECO TRIDIMENSIONAL	' },
{ value: 	165	, label: '	TAC MACIZO FACIAL MULTICORTE	' },
{ value: 	166	, label: '	TAC DE PELVIS CON/CTE MULTICORTE	' },
{ value: 	167	, label: '	TAC DE PELVIS SIN /CTE MULTICORTE	' },
{ value: 	168	, label: '	TAC DE PLATILLO TIBIAL MULTICORTE	' },
{ value: 	169	, label: '	PUNCION TRANSRECTAL	' },
{ value: 	172	, label: '	ECO PELVIANA	' },
{ value: 	174	, label: '	RECAMBIO DE CATETER	' },
{ value: 	176	, label: '	PUNCION PANCREATICA	' },
{ value: 	177	, label: '	PUNCION DRENAJE Y COLOCACION DE STENT	' },
{ value: 	179	, label: '	ECO INGUINAL	' },
{ value: 	180	, label: '	ECO DE REGION UMBILICAL	' },
{ value: 	181	, label: '	TAC DE OTROS ORGANOS MULTICORTE	' },
{ value: 	183	, label: '	RX APARATO URINARIO	' },
{ value: 	184	, label: '	TAC DE ABDOMEN Y TORAX MULTICORTE	' },
{ value: 	185	, label: '	COLOGRAFIA DISTAL	' },
{ value: 	188	, label: '	PROGRESION DE SONDA	' },
{ value: 	189	, label: '	TAC DE CUELLO MULTICORTE	' },
{ value: 	192	, label: '	PUNCION PELVIANA	' },
{ value: 	195	, label: '	ECO PENEANA	' },
{ value: 	197	, label: '	TAC ANTEPIE MULTICORTE	' },
{ value: 	201	, label: '	TAC DE AMBOS PIES MULTICORTE	' },
{ value: 	203	, label: '	TAC PARA MEDICION DE MMII MULTICORTE	' },
{ value: 	204	, label: '	TAC CEREBRO/COLUMNA CERVICAL MULTICORTE	' },
{ value: 	205	, label: '	TAC CERVICODORSAL MULTICORTE	' },
{ value: 	206	, label: '	TAC TOBILLO MULTICORTE	' },
{ value: 	207	, label: '	ECO DOPPLER OCULAR	' },
{ value: 	208	, label: '	TAC DE FOSAS NASALES Y CAVUM MULTICORTE	' },
{ value: 	210	, label: '	DESINVAGINACION	' },
{ value: 	211	, label: '	COLOCACIÓN DE CATÉTER O DRENAJE GUIADO	' },
{ value: 	212	, label: '	TAC FOSAS NASALES Y SENOS PARANASALES MULTICORTE	' },
{ value: 	213	, label: '	TAC ABDOMEN/TORAX S/CTE MULTICORTE	' },
{ value: 	216	, label: '	ECO DOPPLER DE PARTES BLANDAS	' },
{ value: 	218	, label: '	PUNCION DE PARED ABDOMINAL	' },
{ value: 	219	, label: '	ECO VESICAL	' },
{ value: 	220	, label: '	TAC DE CODO MULTICORTE	' },
{ value: 	221	, label: '	TAC CUELLO/TORAX/MACIZO FACIAL MULTICORTE	' },
{ value: 	222	, label: '	PIELOTAC	' },
{ value: 	223	, label: '	TAC ESCAPULA MULTICORTE	' },
{ value: 	225	, label: '	TAC ABDOMEN/TORAX C/CTE MULTICORTE	' },
{ value: 	227	, label: '	TAC CEREBRO/ TORAX/ ABDOMEN/ PELVIS MULTICORTE	' },
{ value: 	228	, label: '	PUNCION DE MEDIASTINO	' },
{ value: 	231	, label: '	ECO DOPPLER DE ARTERIA UMBILICAL	' },
{ value: 	232	, label: '	ECO DOPPLER DE MMII VENOSO	' },
{ value: 	233	, label: '	TAC CEREBRO/CUELLO C/CTTE MULTICORTE	' },
{ value: 	234	, label: '	TAC DE CLAVÍCULA MULTICORTE	' },
];


