

export default [
    { value:	1	, label: '	EQUIPOS	 ' },
{ value:	2	, label: '	FARMACIA	 ' },
{ value:	3	, label: '	LABORATORIO	 ' },
{ value:	4	, label: '	CENTRO MEDICO VITUS	 ' },
{ value:	5	, label: '	SANTIAGO, RICARDO JOSE	 ' },
{ value:	6	, label: '	ROJAS, DANIEL	 ' },
{ value:	7	, label: '	FLACHS CAROLINA	 ' },
{ value:	8	, label: '	GANDOLFO ALFREDO ANTONIO	 ' },
{ value:	10	, label: '	TERNENGO DIEGO	 ' },
{ value:	11	, label: '	LADA PAUL EDUARDO	 ' },
{ value:	12	, label: '	MASSA SILVIO MARTIN	 ' },
{ value:	13	, label: '	ROMERO DIAZ EUGENIO	 ' },
{ value:	14	, label: '	SOSA NATALIA LORENA	 ' },
{ value:	15	, label: '	ZIPEROVICH CYNTIA	 ' },
{ value:	16	, label: '	DE BENITO ANDRES	 ' },
{ value:	17	, label: '	OJEDA VERONICA	 ' },
{ value:	19	, label: '	LEDESMA MARTA	 ' },
{ value:	20	, label: '	VERA CAROLINA	 ' },
{ value:	22	, label: '	GRENAT ANDRES	 ' },
{ value:	23	, label: '	BARRON MARIA BELEN	 ' },
{ value:	24	, label: '	MARTINATTO CAROLINA	 ' },
{ value:	25	, label: '	ESCALERA JOSE	 ' },
{ value:	26	, label: '	ELIAS MARIELA VIVIANA	 ' },
{ value:	27	, label: '	SASTRE SILVINA ANALIA	 ' },
{ value:	28	, label: '	GOROSTIAGA LUCIANA	 ' },
{ value:	30	, label: '	WERNER MARINA	 ' },
{ value:	31	, label: '	DIAZ JORGE	 ' },
{ value:	32	, label: '	VEGA MARCELO	 ' },
{ value:	33	, label: '	LOPEZ LOZANO TRISTAN	 ' },
{ value:	34	, label: '	DALVIT KARINE MAMOGRAFIA	 ' },
{ value:	35	, label: '	GARCIA VELEZ MANUEL	 ' },
{ value:	36	, label: '	CANAVOSIO NICOLAS ECOGRAFIA	 ' },
{ value:	40	, label: '	SONZINI ASTUDILLO CRISTIAN	 ' },
{ value:	41	, label: '	PISANO ROBERTO	 ' },
{ value:	42	, label: '	PAUTASSO SANTIAGO	 ' },
{ value:	43	, label: '	PINTO GABRIEL	 ' },
{ value:	44	, label: '	CORDEIRO ERNESTO RAUL	 ' },
{ value:	46	, label: '	BERNABEU FRANCISCO	 ' },
{ value:	47	, label: '	GREPPI NATALIA	 ' },
{ value:	48	, label: '	FUENTES ANABELLA	 ' },
{ value:	49	, label: '	PONS MACARENA	 ' },
{ value:	50	, label: '	DEL CASTILLO ANDRES	 ' },
{ value:	52	, label: '	ECOGRAFIA 1 - CEJAS HUGO	 ' },
{ value:	53	, label: '	HADAD ANDRES	 ' },
{ value:	54	, label: '	TORTOLO GABRIELA	 ' },
{ value:	55	, label: '	QUIROFANO 1	 ' },
{ value:	57	, label: '	GLATSTEIN ANIBAL (P)	 ' },
{ value:	58	, label: '	CAMPETTI FERNANDA (P)	 ' },
{ value:	59	, label: '	SARSFIELD MARCELO (P)	 ' },
{ value:	60	, label: '	VALENCI JUDITH (P)	 ' },
{ value:	61	, label: '	VIDART AYELEN (P)	 ' },
{ value:	62	, label: '	MALDONADO SILVINA (P)	 ' },
{ value:	63	, label: '	FLUJOMETRIA	 ' },
{ value:	64	, label: '	BAZAN MARTA	 ' },
{ value:	65	, label: '	DEL BOCA SILVINA	 ' },
{ value:	66	, label: '	RAIDEN MIRTHA (P)	 ' },
{ value:	67	, label: '	ARABIA LUIS	 ' },
{ value:	68	, label: '	MORISSE DANIEL	 ' },
{ value:	69	, label: '	TREGNAGHI MIGUEL	 ' },
{ value:	70	, label: '	TREGNAGHI MARCELO	 ' },
{ value:	71	, label: '	TREGNAGHI PABLO	 ' },
{ value:	72	, label: '	VANADIA PAULA	 ' },
{ value:	73	, label: '	BARMAT GABRIELA	 ' },
{ value:	74	, label: '	DAGHERO ANDREA	 ' },
{ value:	75	, label: '	CATALANI ANDREA (P)	 ' },
{ value:	76	, label: '	MARCHEGIANI SILVIO- ECOGRAFIAS	 ' },
{ value:	77	, label: '	CEJAS HUGO	 ' },
{ value:	78	, label: '	ALE MARTIN	 ' },
{ value:	79	, label: '	LORENZATTI LUCAS	 ' },
{ value:	80	, label: '	MAGLIONE MARIO	 ' },
{ value:	81	, label: '	PISANO FLORENCIA	 ' },
{ value:	82	, label: '	RIBOTTA BETIANA IVON	 ' },
{ value:	83	, label: '	PEDIATRICA SRL	 ' },
{ value:	84	, label: '	CHEQUEOS PREVENTIVOS	 ' },
{ value:	85	, label: '	MORISSE DANIEL - ECO DOPPLER	 ' },
{ value:	86	, label: '	MARCHEGIANI SILVIO- RADIOLOGIA	 ' },
{ value:	87	, label: '	ROMERO DIAZ EUGENIO - DOPPLER	 ' },
{ value:	88	, label: '	GALLO MONICA	 ' },
{ value:	89	, label: '	BERARDO ANDRES IGNACIO	 ' },
{ value:	90	, label: '	CHEQUEO CPCE	 ' },
{ value:	91	, label: '	ESTUDIOS DE HEMATOLOGIA	 ' },
{ value:	92	, label: '	UROLOGIA	 ' },
{ value:	93	, label: '	PEREZ SOLEDAD - RADIOLOGIA	 ' },
{ value:	94	, label: '	PEREZ SOLEDAD - ECOGRAFIAS	 ' },
{ value:	95	, label: '	LACE SRL	 ' },
{ value:	96	, label: '	CORTIZO GUSTAVO	 ' },
{ value:	97	, label: '	TESTI QUIROS RICARDO	 ' },
{ value:	98	, label: '	BENGIO VERONICA ANATOMIA PATOL	 ' },
{ value:	99	, label: '	ESTRADA MUCCI ALEJANDRO	 ' },
{ value:	100	, label: '	MARTINEZ GUSTAVO	 ' },
{ value:	101	, label: '	EPELDE JAVIER ALEJANDRO	 ' },
{ value:	102	, label: '	CORDERO ESTEBAN	 ' },
{ value:	103	, label: '	ECODOPPLER CORTIZO GUSTAVO	 ' },
{ value:	104	, label: '	OSDE CHEQUEOS	 ' },
{ value:	105	, label: '	FERRERO PAOLA	 ' },
{ value:	106	, label: '	VALLE PABLO	 ' },
{ value:	107	, label: '	MADRID MATIAS	 ' },
{ value:	108	, label: '	CARUSO GUSTAVO	 ' },
{ value:	109	, label: '	CHEQUEOS PARTICULARES	 ' },
{ value:	110	, label: '	ROQUE MARTIN HECTOR	 ' },
{ value:	111	, label: '	DACREMA JULIETA INES	 ' },
{ value:	112	, label: '	CORTIZO GUSTAVO ECO DOPPLER	 ' },
{ value:	113	, label: '	MONTALDO ANA	 ' },
{ value:	114	, label: '	CANAVOSIO NICOLAS RADIOGRAFIA	 ' },
{ value:	115	, label: '	MORETTI GASTON	 ' },
{ value:	116	, label: '	SAVATSKY AGUSTINA	 ' },
{ value:	117	, label: '	VEGA ANA LAURA	 ' },
{ value:	118	, label: '	ROMERO ALEM MARIA TAMARA	 ' },
{ value:	119	, label: '	DALVIT KARINE RADIOLOGIA	 ' },
{ value:	120	, label: '	LEDESMA MARTIN	 ' },
{ value:	121	, label: '	RODRIGUEZ EVA	 ' },
{ value:	122	, label: '	HERNANDEZ MAGDALENA	 ' },
{ value:	123	, label: '	GALVEZ AMALIA	 ' },
{ value:	124	, label: '	GRUTADAURIA MARIA GRACIA	 ' },
{ value:	125	, label: '	PREOCUPACIONAL	 ' },
{ value:	126	, label: '	SUPPO MILENA	 ' },
{ value:	127	, label: '	PARISI GUSTAVO	 ' },
{ value:	128	, label: '	PREOCUPACIONAL OLAPIC	 ' },
{ value:	129	, label: '	PARISSI GUSTAVO ECO DOPPLER	 ' },
{ value:	130	, label: '	CENTRO MEDICO CID	 ' },
{ value:	131	, label: '	SARJANOVICH MARIO RUBEN	 ' },
{ value:	132	, label: '	CARDONA SEBASTIAN	 ' },
{ value:	133	, label: '	ORTIZ ANA MARIA DEL ROSARIO	 ' },
{ value:	134	, label: '	CIRICO CUBARLE DANIELA	 ' },
{ value:	135	, label: '	LOYOLA PABLO	 ' },
{ value:	136	, label: '	CID DALVIT	 ' },
{ value:	137	, label: '	MARISTANY CAROLINA NATHALIA	 ' },
{ value:	138	, label: '	VITTORE BLAS GASTON ECOGRAFIAS	 ' },
{ value:	139	, label: '	VITTORE BLAS GASTON RADIOLOGIA	 ' },
{ value:	140	, label: '	ANCOCHEA PAOLA DESIREE	 ' },
{ value:	141	, label: '	PAUSA PREVENTIVA PARTICULARES	 ' },
{ value:	142	, label: '	FAGALDE NICOLAS	 ' },
{ value:	143	, label: '	TORRES EMILIANO	 ' },
{ value:	144	, label: '	QUINTANA ORSINI CARLOS BRUNO	 ' },
{ value:	145	, label: '	CERTIFICADOS ESCOLARES	 ' },
{ value:	146	, label: '	MARASCHIO MARTIN ALEJANDRO	 ' },
{ value:	147	, label: '	CAGNOLO PAMELA	 ' },
{ value:	148	, label: '	PEREYRA NATALIA LORENA	 ' },
{ value:	149	, label: '	DIEGUEZ ALIAGA FEDERICO	 ' },
{ value:	150	, label: '	BAGNIS MARIA FLORENCIA	 ' },
{ value:	151	, label: '	USIN DOMINGO	 ' },
{ value:	152	, label: '	ABRATE VANESA	 ' },
{ value:	153	, label: '	USIN DOMINGO ECO DOPPLER	 ' },
{ value:	154	, label: '	BATTEZZATI DANIEL	 ' },
{ value:	155	, label: '	MAPA DR BERNABEU	 ' },
{ value:	156	, label: '	ALE MARTIN CONSULTORIO	 ' },
{ value:	157	, label: '	FASSI MARIA ELENA	 ' },
{ value:	158	, label: '	PILAN FRANCISCO	 ' },
{ value:	159	, label: '	BIASONI ANA CAROLINA	 ' },
{ value:	160	, label: '	RIOS RAMIRO	 ' },
{ value:	161	, label: '	OCROGLICH GISELE FABIANA	 ' },
{ value:	162	, label: '	MARIÑO JOSE DAVID ECOGRAFIA	 ' },
{ value:	163	, label: '	MARIÑO JOSE DAVID RADIOLOGÍA	 ' },
{ value:	164	, label: '	ORTUBIA MARIA JIMENA	 ' },
{ value:	165	, label: '	OTERO ALVAREZ DANIELA	 ' },
{ value:	166	, label: '	VIÑUALES ARANBURU MAURO	 ' },
{ value:	167	, label: '	AGUERO JORGE JAVIER NICOLAS	 ' },
{ value:	168	, label: '	MACHADO EZEQUIEL	 ' },
{ value:	169	, label: '	GOZALVEZ NADIA	 ' },
{ value:	170	, label: '	FERNANDEZ ANA PAULA	 ' },
{ value:	171	, label: '	CISNEROS JAVIER ECOGRAFIAS	 ' },
{ value:	172	, label: '	BAROTTO JUAN MARTIN	 ' },
{ value:	173	, label: '	TIRANTINO ANNET MARCELA	 ' },
{ value:	174	, label: '	CISNEROS JAVIER RADIOLOGIA	 ' },
{ value:	175	, label: '	ECHENIQUE GASTON	 ' },
{ value:	176	, label: '	NARVAEZ GISELE	 ' },
{ value:	177	, label: '	LIENDO CAROLINA ALEJANDRA	 ' },
{ value:	178	, label: '	TINARI MARIA BELEN	 ' },
{ value:	179	, label: '	PAIRONE GEORGINA LAURA	 ' },
{ value:	180	, label: '	LUCERO CECILIA BEATRIZ	 ' },
{ value:	181	, label: '	ALVARENGA JOSE	 ' },
{ value:	182	, label: '	CALDERON  GUADALUPE	 ' },
{ value:	183	, label: '	OCROGLICH BERTA FABIANA	 ' },
{ value:	184	, label: '	SAITUA SANTIAGO	 ' },
{ value:	185	, label: '	PADILLA FEDERICO ECOGRAFIA	 ' },
{ value:	186	, label: '	GARCIA FERNANDEZ ANGEL EDUARDO	 ' },
{ value:	187	, label: '	MANGER SILVIA ADRIANA	 ' },
{ value:	188	, label: '	VALLEJO SERGIO GUILLERMO	 ' },
{ value:	189	, label: '	ELECTROENCEFALOGRAMA LUCERO	 ' },
{ value:	190	, label: '	FRIAS MARIA JESUS	 ' },
{ value:	191	, label: '	BERNARDI FEDERICO ECOGRAFIAS	 ' },
{ value:	192	, label: '	ZUFIAURRE JENNIFER	 ' },
{ value:	193	, label: '	LICARI ROXANA VANESA	 ' },
{ value:	194	, label: '	FRANCIULLI NICOLAS ARMANDO	 ' },
{ value:	195	, label: '	BERNARDI FEDERICO RADIOLOGIA	 ' },
{ value:	196	, label: '	BERNARDI FEDERICO MAMOGRAFIAS	 ' },
{ value:	197	, label: '	HOLTER - 24 HORAS	 ' },
{ value:	198	, label: '	NUÑEZ CECILIA	 ' },
{ value:	199	, label: '	SERVICIO DE NEOROLOGIA	 ' },
{ value:	200	, label: '	RICHARDSON NICOLAS	 ' },
{ value:	201	, label: '	LAHOZ  MARIA JOSE	 ' },
{ value:	202	, label: '	ABBURRA MARIA LAURA	 ' },
{ value:	203	, label: '	SERVICIO ODONTOLOGIA	 ' },
{ value:	204	, label: '	SERVICIO DE OFTALMOLOGIA	 ' },
{ value:	205	, label: '	REIMONDEZ SANTIAGO	 ' },
{ value:	206	, label: '	CARVEL GERARDO ALEJANDRO	 ' },
{ value:	207	, label: '	REINARES LAURA AYLEN	 ' },
{ value:	208	, label: '	CAMINOS CINTIA C	 ' },
{ value:	209	, label: '	CASTROMAGGI LORENA	 ' },
{ value:	210	, label: '	ATENCION ESPONTANEA	 ' },
{ value:	211	, label: '	HERNANDEZ GREGORIO	 ' },
{ value:	212	, label: '	CASARES GONZALO EZEQUIEL	 ' },
{ value:	213	, label: '	MARTINEZ PELUAGA MATIAS JULIAN	 ' },
{ value:	214	, label: '	TISSERA GABRIELA	 ' },
{ value:	215	, label: '	GONZALEZ CLAUDIA	 ' },
{ value:	216	, label: '	CARRANZA DARIO	 ' },
{ value:	217	, label: '	GATICA JORGE AGUSTIN	 ' },
{ value:	218	, label: '	MASSARI PABLO ULISES	 ' },
{ value:	219	, label: '	GARCIA MARIA CELESTE	 ' },
{ value:	220	, label: '	CASAGRANDE GUILLERMO	 ' },
{ value:	221	, label: '	GARIN VALERIA INES	 ' },
{ value:	222	, label: '	DAGA ELIANA	 ' },
{ value:	223	, label: '	DEGIORGI NICOLAS OMAR	 ' },
{ value:	224	, label: '	RODOLFI TUZINKEVICZ ERIKA	 ' },
{ value:	225	, label: '	PETINARI  MIRTA SUSANA	 ' },
{ value:	226	, label: '	VERA ROLDAN VALLY LUZ	 ' },
{ value:	227	, label: '	ROMERO MARIA EUGENIA	 ' },
{ value:	228	, label: '	CARIGNANI GIANNA	 ' },
{ value:	229	, label: '	VIDOTTO SCHMIDT NIEVES MARIA	 ' },
{ value:	230	, label: '	MAPA DRA PETTINARI	 ' },
{ value:	231	, label: '	NIEVA DAIANA ANDREA	 ' },
{ value:	232	, label: '	SCALTRITTI ANA LORENA	 ' },
{ value:	233	, label: '	FAIFER ALEJANDRO	 ' },
{ value:	234	, label: '	BARBERO  CAROLINA	 ' },
{ value:	235	, label: '	PALADINI ANA PAULINA	 ' },
];


